# Generated by Django 5.2 on 2025-07-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_cash', models.IntegerField(default=0)),
                ('stock_amount', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('profits', models.IntegerField(default=0)),
                ('development', models.IntegerField(default=0)),
            ],
        ),
    ]
