# Generated by Django 5.2 on 2025-07-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('item', models.CharField(max_length=100)),
                ('qty', models.IntegerField(max_length=100)),
                ('total_buying_price', models.IntegerField(max_length=100)),
                ('buying_price_each', models.IntegerField(max_length=100)),
                ('selling_price_each', models.IntegerField(max_length=100)),
                ('profits_each', models.IntegerField(max_length=100)),
                ('total_selling_price', models.IntegerField(max_length=100)),
                ('total_profits', models.IntegerField(max_length=100)),
            ],
        ),
    ]
