# Generated by Django 5.2 on 2025-07-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_expenditure_itemlist_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlist',
            name='item',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
