# Generated by Django 5.2 on 2025-08-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_itemlist_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='current_stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='profits_each',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='stock',
            name='qty',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='selling_price_each',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='stock',
            name='total_buying_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='total_profits',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='stock',
            name='total_selling_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
