# Generated by Django 5.2 on 2025-08-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_stock_current_stock_alter_stock_profits_each_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='buying_price_each',
            field=models.IntegerField(),
        ),
    ]
