# Generated by Django 5.2 on 2025-08-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_availablestock_buying_price_each_alter_sales_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablestock',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='sales',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
